 tour:
    image: postgres:latest
    command: postgres -c 'max_connections=1000'
    volumes:
      - /var/local/sdb/tour:/var/lib/postgresql/data
    container_name: tour
    ports:
      - "5445:5432"
    environment:
      - POSTGRES_USER=morgan
      - POSTGRES_DB=tour
      - POSTGRES_PASSWORD=test
    restart: unless-stopped

 redis:
    image: redis:6.0
    ports:
      - 6380:6380
 mongodb:
   image: mongo:6-jammy
   ports:
    - '27017:27017'
   volumes:
      - /var/local/sdb/mongo:/data/db

