name: found_travell
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  outline_gradient_button: ^2.0.0+1
  intl: ^0.17.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  get: ^4.6.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Alumni Sans
      fonts:
        - asset: assets/fonts/AlumniSansRomanMedium.ttf
          weight: 500

